# Generated by Django 5.2.11 on 2026-03-22 17:50

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline shown on showcase",
                        max_length=200,
                    ),
                ),
                (
                    "showcase_bio",
                    models.TextField(
                        blank=True, help_text="Longer rich-text bio for showcase page"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                (
                    "aadhar_number",
                    models.CharField(
                        blank=True, help_text="Aadhar Card ID number", max_length=20
                    ),
                ),
                (
                    "aadhar_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional Aadhar Card image upload",
                        null=True,
                        upload_to="aadhar/",
                        validators=[core.validators.validate_image_upload],
                    ),
                ),
                (
                    "location_city",
                    models.CharField(
                        blank=True,
                        help_text="City for discovery features",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("privacy_name", models.BooleanField(default=True)),
                ("privacy_email", models.BooleanField(default=False)),
                ("privacy_hosted_events", models.BooleanField(default=True)),
                ("privacy_serviced_events", models.BooleanField(default=True)),
                ("privacy_events_attending", models.BooleanField(default=True)),
                ("privacy_events_attended", models.BooleanField(default=True)),
                ("allow_private_messages", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
