# Generated by Django 5.2.11 on 2026-03-07 05:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_is_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="aadhar_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional Aadhar Card image upload",
                null=True,
                upload_to="aadhar/",
                validators=[core.validators.validate_image_upload],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="aadhar_number",
            field=models.CharField(
                blank=True, help_text="Aadhar Card ID number", max_length=20
            ),
        ),
    ]
