# Generated by Django 5.2.11 on 2026-03-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_userprofile_aadhar_image_userprofile_aadhar_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_private_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_events_attended",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_events_attending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_hosted_events",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_name",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="privacy_serviced_events",
            field=models.BooleanField(default=True),
        ),
    ]
