# Generated by Django 5.2.11 on 2026-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_lifecycle_state_eventlifecycletransition"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="check_in_instructions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("at_risk", "At Risk"),
                    ("postponed", "Postponed"),
                    ("event_ready", "Event Ready"),
                    ("live", "Live"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventlifecycletransition",
            name="from_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("at_risk", "At Risk"),
                    ("postponed", "Postponed"),
                    ("event_ready", "Event Ready"),
                    ("live", "Live"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventlifecycletransition",
            name="to_state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("at_risk", "At Risk"),
                    ("postponed", "Postponed"),
                    ("event_ready", "Event Ready"),
                    ("live", "Live"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
