# Generated by Django 5.2.11 on 2026-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_check_in_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_ready_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
