# Generated by Django 5.2.11 on 2026-03-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_eventhighlight_eventseries_event_series_eventreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="occurrence_index",
            field=models.PositiveIntegerField(
                blank=True, help_text="1-based sequence inside a series", null=True
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="default_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="default_location_address",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="default_location_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="default_ticket_price_flexible",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="default_ticket_price_standard",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="recurrence_rule",
            field=models.CharField(
                blank=True, help_text="e.g. FREQ=WEEKLY;BYDAY=SU", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="timezone",
            field=models.CharField(default="UTC", max_length=100),
        ),
        migrations.CreateModel(
            name="EventSeriesNeedTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="e.g. DJ, Photographer", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="other", max_length=100)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("essential", "Essential"),
                            ("replaceable", "Replaceable"),
                            ("non_substitutable", "Non-Substitutable"),
                        ],
                        default="replaceable",
                        max_length=20,
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="need_templates",
                        to="events.eventseries",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
