# Generated by Django 5.2.11 on 2026-03-02 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_occurrence_index_eventseries_default_capacity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gallery", "Gallery (Pre-event/Marketing)"),
                            ("highlight", "Highlight (Post-event)"),
                        ],
                        default="gallery",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="events/media/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordering for display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event Media",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
