# Generated by Django 5.2.11 on 2026-03-07 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_eventview"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicketTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="gray", max_length=50)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null means unlimited for this tier",
                        null=True,
                    ),
                ),
                ("is_refundable", models.BooleanField(default=False)),
                ("refund_percentage", models.PositiveIntegerField(default=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_tiers",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["price", "name"],
            },
        ),
    ]
