# Generated by Django 5.2.11 on 2026-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_eventtickettier"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtickettier",
            name="admits",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of people this ticket admits"
            ),
        ),
        migrations.AddField(
            model_name="eventtickettier",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
