# Generated by Django 5.2.11 on 2026-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_eventtickettier_admits_eventtickettier_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticket_price_flexible",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy field. Use TicketTiers instead.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_price_standard",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy field. Use TicketTiers instead. Null means free.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventseries",
            name="default_ticket_price_flexible",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy. Use Tier templates.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventseries",
            name="default_ticket_price_standard",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Legacy. Use Tier templates.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
