# Generated by Django 5.2.11 on 2026-03-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_ticket_price_flexible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {name, tag} dicts for event features (e.g. food, music).",
            ),
        ),
    ]
