# Generated by Django 5.2.11 on 2026-03-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_eventreviewcomment_eventreviewlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtickettier",
            name="max_passes_per_ticket",
            field=models.PositiveIntegerField(
                default=6, help_text="Maximum tickets per transaction for this tier"
            ),
        ),
    ]
