# Generated by Django 5.2.11 on 2026-03-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0020_friendship"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addon_slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("event", "addon_slug")},
            },
        ),
    ]
