# Generated by Django 5.2.11 on 2026-03-22 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSpecialGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chat_special_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_special_group",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("thread_key", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_event_public_chat_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages_public",
                        to="events.event",
                    ),
                ),
                (
                    "recipient_event_vendor_group_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages_vendor",
                        to="events.event",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages_received_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_special_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatspecialgroup",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "indexes": [
                    models.Index(
                        fields=["thread_key", "-created_at"],
                        name="chat_msg_thread_created_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("recipient_event_public_chat_event_id__isnull", True),
                                ("recipient_event_vendor_group_event_id__isnull", True),
                                ("recipient_special_group_id__isnull", True),
                                ("recipient_user_id__isnull", False),
                            ),
                            models.Q(
                                ("recipient_event_public_chat_event_id__isnull", False),
                                ("recipient_event_vendor_group_event_id__isnull", True),
                                ("recipient_special_group_id__isnull", True),
                                ("recipient_user_id__isnull", True),
                            ),
                            models.Q(
                                ("recipient_event_public_chat_event_id__isnull", True),
                                (
                                    "recipient_event_vendor_group_event_id__isnull",
                                    False,
                                ),
                                ("recipient_special_group_id__isnull", True),
                                ("recipient_user_id__isnull", True),
                            ),
                            models.Q(
                                ("recipient_event_public_chat_event_id__isnull", True),
                                ("recipient_event_vendor_group_event_id__isnull", True),
                                ("recipient_special_group_id__isnull", False),
                                ("recipient_user_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chat_message_single_recipient_shape",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatSpecialGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="chat.chatspecialgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_special_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_special_group_member",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "user"),
                        name="chat_special_group_member_group_user_uniq",
                    )
                ],
            },
        ),
    ]
