# Generated by Django 5.2.11 on 2026-03-22 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_type", models.CharField(default="standard", max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color based on ticket level",
                        max_length=20,
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        blank=True, help_text="Name of the guest", max_length=200
                    ),
                ),
                (
                    "is_18_plus",
                    models.BooleanField(default=False, help_text="Is the guest 18+?"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "qr_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret used to sign the QR token",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("is_refundable", models.BooleanField(default=False)),
                (
                    "refund_percentage",
                    models.PositiveIntegerField(
                        default=100, help_text="Percentage to refund, 0-100"
                    ),
                ),
                ("refund_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "price_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ticket was admitted/scanned",
                        null=True,
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Host who admitted this ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admitted_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="events.event",
                    ),
                ),
                (
                    "goer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="events.eventtickettier",
                    ),
                ),
            ],
        ),
    ]
