# Generated by Django 5.2.11 on 2026-03-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ticket",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="color",
            field=models.CharField(
                default="gray", help_text="Color based on ticket level", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="guest_name",
            field=models.CharField(
                blank=True, help_text="Name of the guest", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_18_plus",
            field=models.BooleanField(default=False, help_text="Is the guest 18+?"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="refund_percentage",
            field=models.PositiveIntegerField(
                default=100, help_text="Percentage to refund, 0-100"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (Non-Refundable)"),
                    ("flexible", "Flexible (Refundable)"),
                ],
                default="standard",
                max_length=50,
            ),
        ),
    ]
