# Generated by Django 5.2.11 on 2026-03-07 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_ticket_price_flexible_and_more"),
        ("tickets", "0002_alter_ticket_unique_together_ticket_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="events.eventtickettier",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(default="standard", max_length=100),
        ),
    ]
