# Generated by Django 5.2.11 on 2026-03-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_tier_alter_ticket_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
