# Generated by Django 5.2.11 on 2026-03-08 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admitted_by',
            field=models.ForeignKey(blank=True, help_text='Host who admitted this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket was admitted/scanned', null=True),
        ),
    ]
