# Generated by Django 5.2.11 on 2026-03-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_secret',
            field=models.CharField(blank=True, help_text='Secret used to sign the QR token', max_length=64, null=True),
        ),
    ]
