# Generated by Django 5.2.11 on 2026-03-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("needs", "0002_needinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventneed",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                    ("override_filled", "Override Filled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
