# Generated by Django 5.2.11 on 2026-03-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("needs", "0003_alter_eventneed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="needapplication",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="needapplication",
            name="qr_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret used to sign the QR token",
                max_length=64,
                null=True,
            ),
        ),
    ]
