# Generated by Django 5.2.11 on 2026-03-09 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("needs", "0004_needapplication_barcode_needapplication_qr_secret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="needapplication",
            name="admitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="needapplication",
            name="admitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admitted_vendors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
